# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CricTrac' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CricTrack

pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'

pod 'FBSDKLoginKit'
pod 'GoogleSignIn'

pod 'IOStickyHeader'
pod 'KYDrawerController'
pod 'CSStickyHeaderFlowLayout'
pod 'SkyFloatingLabelTextField', '~> 1.0'

pod 'SCLAlertView'
end
