# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CricTrac' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CricTrack

pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'

pod 'Fabric'
pod 'Crashlytics'

pod 'FBSDKLoginKit'
pod 'GoogleSignIn'


pod 'KYDrawerController'

pod 'SkyFloatingLabelTextField', '~> 1.0'

pod 'SCLAlertView'
pod "KRProgressHUD"

pod 'XLPagerTabStrip', '~> 5.0'
pod 'AnimatedTextInput', '~> 0.3.0'
pod 'SwiftCountryPicker'
pod "XMExpandableTableView"
end
