# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, "9.0"
use_frameworks!
target 'CricTrac' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for CricTrack

pod 'Firebase', '3.11.1'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Fabric'
pod 'Crashlytics'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit’
pod 'GoogleSignIn'
pod 'SwiftyJSON', '2.4.0'
pod 'IQKeyboardManagerSwift', '4.0.5'
pod 'KYDrawerController’, :git => ‘https://github.com/ykyouhei/KYDrawerController.git', :branch => ‘develop’

pod 'SkyFloatingLabelTextField', '~> 1.0'

pod 'SCLAlertView',  :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git', :branch => 'swift-2.3'
pod 'KRProgressHUD', :git => 'https://github.com/krimpedance/KRProgressHUD.git', :branch => 'swift2.3'
pod 'XLPagerTabStrip', '~> 5.0'
pod 'AnimatedTextInput', '~> 0.3.0'
pod 'SwiftCountryPicker', '1.0.0'

pod 'KeychainSwift', git: "https://github.com/marketplacer/keychain-swift.git", branch: "swift_2_3"

end
